### ISSUE TITLE
2.5.2 have error

### ISSUE THREAD

**Issue by pinghe** [kristianmandrup/vue2-dragula#25]
"Uncaught TypeError: this.calcOpts is not a function".

In version 2.5.2, the example, vue2-dragula-demo,  does not work

**Comment by pinghe** [comment]
In version 2.5.3, this bug still exists

**Comment by kristianmandrup** [comment]
Fixed in latest `2.5.4`. Also tried to fix the long standing problem with `copy` copying items twice, still no success.

Fixed the demo to use v-bind for keys `:key="text"` in `v-for` loops as required my ~ Vue 2.2+.
The categories is also broken. Used to work without keys (nested arrays, but now using keys, sth is broken). I need some help maintaining this lib. I haven't worked with Vue 2 for a long time, so no longer on top of changes to the internals, APIs etc.
