### ISSUE TITLE
More example 

### ISSUE THREAD

**Issue by minedun6** [kristianmandrup/vue2-dragula#26]
Is it possible to get an example showcasing multiple list, like a kanban board ?
What would be great is to see how to wire it with events so that we can later send the data to the backend ? Not using local storage though.
I have a working example using Vue.Draggable that is great but lacks customisation when it comes to ui.
Here's the rep if you wanna take a look. it uses Laravel as backend.

[Trello-clone](https://github.com/minedun6/trello-clone/tree/tailwindcss)

**Comment by kristianmandrup** [comment]
Hi @minedun6. Thanks, I like your idea. It was my original intention to use this library for sth like that. For now the issue would first be to fix the `copy` bug as noted. I don't really understand the Vue change detection. I think instead of using splice on the array in the ModelManager, a new array (pointer) should be created and then potentially use `Vue.set` to force Vue to re-render based on the new value. Could also be a list keys issue, not sure how they are meant to work either.
Haven't worked with Vue for a very long time now, since switched back to React which I think is much better at this point, having moved on and fixed many of the the original "flaws".

Please add the example you talk about. I have no time to do so myself.
