### ISSUE TITLE
Complicated relationship

### ISSUE THREAD

**Issue by varHarrie** [kristianmandrup/vue2-dragula#7]
After I read the docs in README.md and demo project, it seem to be a powerful dnd lib. But I still not entirely clear the relationship between drake, service and model.

Another problem is whether the `this.$dragula.$service` is not the instanceof `DragulaService`? and why `on` is not a method of `this.$dragula.$service`?

I need you help that to provide a further description. Thank you.

**Comment by kristianmandrup** [comment]
Yes, could be explained better, perhaps with a diagram and flows etc.

I would recommend you look at the demo code examples to get a feel for how easy it is to use and setup. The service interacts with the UI and delegates to Drake for DND and to the ModelManager for managing the underlying model for each dnd action.

Will improve the docs shortly.

**Comment by varHarrie** [comment]
Is it support for `transition-group` or any demo ?

**Comment by kristianmandrup** [comment]
Transition group? Well should be support for any Dragula configuration. Please explain.

**Comment by varHarrie** [comment]
@kristianmandrup Here is [jsfiddle](https://jsfiddle.net/av1jLfn8/)

It's a official `transition-group` demo (from [here](https://vuejs.org/v2/guide/transitions.html#List-Move-Transitions)) and integrates with `vue2-dragula`.

We can see some transition animations when click the bottom buttons (Shuffle, Add, Remove), but it immediately change when drag and drog the item without transition.

**Comment by kristianmandrup** [comment]
Cool ;) So what is the verdict? If it doesn't work as you would expect how can we fix it? What needs to be done?

**Comment by kristianmandrup** [comment]
Got back online with my laptop. Was unable to do dnd with my phone on your example. I see now that there is no animation when doing dnd. You might get a hint as to why if you enabled logging in the example, although it can be overwhelming. The usual examples use 2 lists:
[NamedServices](https://github.com/kristianmandrup/vue2-dragula-demo/blob/master/src/components/NamedServices.vue#L7) but not sure if this is the cause. Likely it is the Vue change detection system not picking up the underlying model change correctly.

For this we need to look into the [ModelManager mutation methods](https://github.com/kristianmandrup/vue2-dragula-demo/blob/master/src/util/model-manager.js#L72) and we see that it acts as an indirection/shield layer so that the elements are not directly linked to the list I think. The [ActionManager](https://github.com/kristianmandrup/vue2-dragula/blob/master/src/action-manager.js) used for undo/redo might currently work better in this regard. In order for the [TimeMachine](https://github.com/kristianmandrup/vue2-dragula/blob/master/src/time-machine.js#L39) to work, I had to manually rebuild the new array with push in order for Vue change detection system to kick in!

I'm not really that experiences with the internals of Vue2. This was my first attempt at a plugin.

Perhaps debugging from here [DragHandler insertAt](https://github.com/kristianmandrup/vue2-dragula/blob/master/src/drag-handler.js#L75) would go a long way...

**Comment by kristianmandrup** [comment]
The service does use `ModelManager` by default as can be seen [here](https://github.com/kristianmandrup/vue2-dragula/blob/master/src/service.js#L31)

**Comment by varHarrie** [comment]
I will try to more practice with your advice when I have free time. Thank for your reply! :smiley:

**Comment by kristianmandrup** [comment]
Would be really awesome if you/we could make Transition groups work!!! :)
